// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftafcstqgihjzddnlasx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0YWZjc3RxZ2loanpkZG5sYXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjQ4ODgsImV4cCI6MjA3NDMwMDg4OH0.jm2vASwkHLWxp9NVAvzgJ8SnRiENIZA8Qp_FBycSFdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});